// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRXFNZ__lWw2W1py87R6NpvbRpXyugwkg',
    appId: '1:566323247151:web:811fa64e415302f6d22eda',
    messagingSenderId: '566323247151',
    projectId: 'fir-authentication-b646c',
    authDomain: 'fir-authentication-b646c.firebaseapp.com',
    storageBucket: 'fir-authentication-b646c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnwPzmwtFJpoKpdBlmYNUI2Xayjs4518',
    appId: '1:566323247151:android:e073e77e0936b638d22eda',
    messagingSenderId: '566323247151',
    projectId: 'fir-authentication-b646c',
    storageBucket: 'fir-authentication-b646c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuOxGI7jGsiUVylcpuNTpeUvrdC7uBds',
    appId: '1:566323247151:ios:47b2b59185fa3541d22eda',
    messagingSenderId: '566323247151',
    projectId: 'fir-authentication-b646c',
    storageBucket: 'fir-authentication-b646c.appspot.com',
    iosBundleId: 'ph.edu.usjr.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuOxGI7jGsiUVylcpuNTpeUvrdC7uBds',
    appId: '1:566323247151:ios:47b2b59185fa3541d22eda',
    messagingSenderId: '566323247151',
    projectId: 'fir-authentication-b646c',
    storageBucket: 'fir-authentication-b646c.appspot.com',
    iosBundleId: 'ph.edu.usjr.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRXFNZ__lWw2W1py87R6NpvbRpXyugwkg',
    appId: '1:566323247151:web:ea66c512b26bf74fd22eda',
    messagingSenderId: '566323247151',
    projectId: 'fir-authentication-b646c',
    authDomain: 'fir-authentication-b646c.firebaseapp.com',
    storageBucket: 'fir-authentication-b646c.appspot.com',
  );
}
